# tomcat
server:
  port: 9001
spring:
  application:
    name: kitty-generator
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.0.16.91:3306/dkywave-kitty?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
      username: root
      password: mysql
beetl:
  templatesPath: templates