# tomcat
server:
  port: 9001
spring:
  application:
    name: kitty-generator
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/charging_db?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
      username: root
      password: mysql
beetl:
  templatesPath: templates